apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.monitoring.customQueriesConfigMap.name }}
  namespace: monitoring
data:
  {{ .Values.monitoring.customQueriesConfigMap.key }}: |
{{ .Files.Get .Values.monitoring.customQueriesConfigMap.file | indent 4 }}