apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-cluster
  namespace: postgres
spec:
  instances: 3

  #imageName: public.ecr.aws/docker/library/postgres:16.4

  # 1. Configuration du stockage AWS gp3
  storage:
    size: 10Gi
    storageClass: "gp3" 

  bootstrap:
    initdb:
      database: devdb
      owner: postgres

  postgresql:
    parameters:
      shared_buffers: "1GB"
      work_mem: "32MB"
      max_connections: "200"