global:
  security:
    allowInsecureImages: true
  imageRegistry: public.ecr.aws

postgresql:
  image:
    registry: public.ecr.aws/bitnami
    repository: bitnami/postgresql
    #tag: 16.4.0
    tag: "16.4.0-debian-12-r23" # Utilise un tag précis et existant

  primary:
    persistence:
      enabled: true
      storageClass: "local-path"
      size: 10Gi

    service:
      type: NodePort
      nodePorts:
        postgresql: 30564

  auth:
    database: "devdb"
    postgresPassword: "postgres123"